// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjelsuxiuyzszirfrpnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqZWxzdXhpdXl6c3ppcmZycG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzkwODAsImV4cCI6MjA3MjMxNTA4MH0.o0XuYSDZKr5laI6RIIYvcjJOUQ0yieWMVugL86NkszU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});